version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: elastic-apm-http-client
    versions:
    - 9.4.3
    - 9.5.0
    - 9.6.0
  - dependency-name: tedious
    versions:
    - 11.0.3
    - 11.0.4
    - 11.0.5
    - 9.2.3
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: read-pkg-up
    versions:
    - 7.0.1
